FROM openresty/openresty:1.13.6.2-2-centos

# Test dependencies.
RUN yum -y install \
  gcc \
  make

# Install locale data for date formatting locale tests. This requires
# changing this yum setting and reinstalling:
# https://serverfault.com/a/884562
RUN sed -i '/override_install_langs/d' /etc/yum.conf && \
  yum -y reinstall glibc-common || yum -y install glibc-common

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

COPY . /app
