FROM openresty/openresty:1.11.2.1-centos

# Test dependencies.
RUN yum -y install \
  gcc \
  make

# Install locale data for date formatting locale tests. This requires
# changing this yum setting and reinstalling:
# https://serverfault.com/a/884562
RUN sed -i '/override_install_langs/d' /etc/yum.conf && \
  yum -y reinstall glibc-common || yum -y install glibc-common

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt

# Set PATH to pickup "luarocks" in this version of OpenResty container.
ENV PATH=/usr/local/openresty/luajit/bin:/usr/local/openresty/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Unset default entrypoint in this version of OpenResty container.
ENTRYPOINT []

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

COPY . /app
