version: 2
jobs:
  openresty-1.13:
    docker:
      - image: openresty/openresty:1.13.6.2-2-centos
    steps:
      - checkout
      - run: yum -y install make
      - run: make install-test-deps-yum
      - run: make install-test-deps
      - run: make test
      # Run the external integration tests, but only on non-forked PRs.
      - run: |
          if [ -z "$CIRCLE_PR_USERNAME" ]; then
            make test-integration-external
          fi
  # Test in older version (ngx_lua pre v0.10.7, OpenResty pre 1.11.2.2) before
  # "settimeouts" support was added.
  openresty-1.11.2.1:
    docker:
      - image: openresty/openresty:1.11.2.1-centos
    environment:
      PATH: /usr/local/openresty/luajit/bin:/usr/local/openresty/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run: yum -y install make
      - run: make install-test-deps-yum
      - run: make install-test-deps
      - run: make test
workflows:
  version: 2
  build:
    jobs:
      - openresty-1.13
      - openresty-1.11.2.1
